Added E2E test case for error

diff --git a/e2e/bitrise.yml b/e2e/bitrise.yml
--- a/e2e/bitrise.yml
+++ b/e2e/bitrise.yml
@@ -11,6 +11,29 @@ workflows:
     after_run:
     - _run
 
+  test_certificate_url_and_passphrase_not_equal:
+    steps:
+    - script:
+        title: Test if the step fails when the Certificate URL count is not equal to Certificate passphrase count
+        inputs:
+        - content: |-
+            #!/bin/env bash
+            set -x # Do not set -e as bitrise command is expected to fail
+            bitrise run --config=./e2e/bitrise.yml utility_certificate_url_and_passphrase_not_equal
+            if [ $? -ne 1 ] ; then
+              echo "Workflow was excepted to fail, exit code not 1."
+              exit 1
+            fi
+
+  utility_certificate_url_and_passphrase_not_equal:
+    envs:
+    - BITRISE_CERTIFICATE_URL_LIST: "https://example.com|https://example.com|https://example.com"
+    - BITRISE_CERTIFICATE_PASSPHRASE_LIST: "test|test|test|test"
+    - BITRISE_PROVISIONING_PROFILE_URL_LIST: $BITRISE_PROVISIONING_PROFILE_URL_LIST
+    - BITRISE_KEYCHAIN_PASSWORD: $BITRISE_KEYCHAIN_PASSWORD
+    after_run:
+    - _run
+
   _run:
     steps:
     - change-workdir:
